Traceback (most recent call last):
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
original = [-1.5, 0.2, 0.4, 0.0, -1.3, 0.4]
result = ____
for value in original:
    if ____:
        result.append(0)
    else:
        ____
            
print(result)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/x0/pvpjfdzd39sc5rqvsk5lvv4m0000gn/T/ipykernel_5651/2135774983.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0moriginal[0m [0;34m=[0m [0;34m[[0m[0;34m-[0m[0;36m1.5[0m[0;34m,[0m [0;36m0.2[0m[0;34m,[0m [0;36m0.4[0m[0;34m,[0m [0;36m0.0[0m[0;34m,[0m [0;34m-[0m[0;36m1.3[0m[0;34m,[0m [0;36m0.4[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mresult[0m [0;34m=[0m [0m____[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mfor[0m [0mvalue[0m [0;32min[0m [0moriginal[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0;32mif[0m [0m____[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m         [0mresult[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name '____' is not defined
NameError: name '____' is not defined

